dbService:
  name: open-imis-db
  port: 5432
  postgresPassword: "IMISuserP@s"
  username: "IMISuser"
  password: "IMISuserP@s"
  database:
    name: "IMIS"

dbStatefulset:
  name: open-imis-db
  spec:
    image: 161826879607.dkr.ecr.eu-central-1.amazonaws.com/open-imis/plg-db:stock
    mountPath: /var/lib/pgsql/data
    storage: 2Gi
secret:
  name: open-imis-secret
