# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.1.2
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  deploy-project:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}
          aws-region: AWS_DEFAULT_REGION
          profile-name: ${AWS_ROLE}
          role-session-name: CircleSession
          session-duration: '1800'
      - helm/install-helm-client:
          version: v3.2.0
      - run:
          name: Update kubectl
          command: |
            aws eks update-kubeconfig --region ${AWS_DEFAULT_REGION} --name ${AWS_CLUSTER_NAME} --role-arn arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}
      - run:
          name: Install chart
          command: |
            helm upgrade --install sandbox-open-imis ./sandbox-open-imis/ --create-namespace --namespace ${CHART_NAMESPACE}

parameters:
  deploy_allowed:
    type: boolean
    default: false

workflows:
  Deploy project to DEV environment:
    when: << pipeline.parameters.deploy_allowed >>
    jobs:
      - hold:
          type: approval
      - deploy-project:
          context: aws
          requires:
            - hold
