postgresConfigMap:
  name: govstack-gdb-postgres-config
  labels:
    app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ${GDB_POSTGRES_ADMIN_SECRET}
postgresStorage:
  volName: govstack-gdb-postgres-pv-volume
  claimName: govstack-gdb-postgres-pv-claim
  labels:
    type: local
    app: postgres
  spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessMode: ReadWriteMany
    hostPath:
      path: "/mnt/data"
postgresDeployment:
  name: govstack-gdb-postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: govstack-gdb-postgres
            image: postgres:12
            imagePullPolicy: "IfNotPresent"
            containerPort: 5432
            configMapRef: govstack-gdb-postgres-config
            volumeMountPath: /var/lib/postgresql/data
            volumeMountName: postgredb
            volumeName: postgredb
            volumeClaimName: govstack-gdb-postgres-pv-claim
        volumes:
          - name: postgredb
            claimName: govstack-gdb-postgres-pv-claim           
postgresService:
  name: govstack-gdb-postgres
  labels:
    app: postgres
  spec:
    type: NodePort
    port: 5432
    selector:
      app: postgres
redisConfigMap:
  name: govstack-gdb-redis-config         
redis:
  name: govstack-gdb-redis
  namespace: ${NAMESPACE}
  containers:
    name: govstack-gdb-redis
    image: redis:6.2.5
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: true
    volumeMounts:
      - mountPath: /redis-master-data
        name: data
      - mountPath: /redis-master
        name: config
  volumes:
    dataName: data
    configName: config
    configMapName: govstack-gdb-redis-config
    configMapItems:
      - key: redis-config
        path: redis.conf               
secret:
  postgres:
    adminPassword:
      name: govstack-gdb-postgres-admin-secret
      type: Opaque
service:
  name: govstack-gdb
  type: ClusterIP
deployment:
  name: govstack-gdb
  containers:
    name: govstack-gdb
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/${ECR_GDB_REPO_NAME}:gdb
    imagePullPolicy: "Always"
    env:
      - name: "ENV"
        value: "LIVE"    
      - name: "DATABASE_HOST"
        value: "${POSTGRES_HOST}"
      - name: "DATABASE_NAME"
        value: "${GDB_POSTGRES_DB_NAME}"
      - name: "DATABASE_USERNAME"
        value: "${GDB_POSTGRES_DB_USER}"
      - name: "DATABASE_PASSWORD"
        value: "${GDB_POSTGRES_DB_PASSWORD}"                     
      - name: "REDIS_HOST"
        value: "${SERVICE_HOST}"
      - name: "ALLOWED_HOSTS"
        value: "gdb.${YOUR_DOMAIN_NAME},gdb,172.19.0.2"        
      - name: "CORS_ORIGIN_WHITELIST"
        value: ""
      - name: "AUTH_SERVICE_TYPE_1"
        value: "KEYCLOAK" 
      - name: "AUTH_SERVICE_REALM_1"
        value: "${SYSTEM_CODE}"
      - name: "AUTH_SERVICE_BACKEND_URL_1"
        value: "http://keycloak:8080" 
      - name: "AUTH_SERVICE_PUBLIC_URL_1"
        value: "https://login.${YOUR_DOMAIN_NAME}/" 
      - name: "AUTH_SERVICE_ID_1"
        value: "0" 
      - name: "AUTH_SERVICE_NAME_1"
        value: "${SYSTEM_CODE}"
      - name: "AUTH_SERVICE_CLIENT_ID_1"
        value: "${GDB_OAUTH_CLIENT_ID}"
      - name: "AUTH_SERVICE_CLIENT_SECRET_1"
        value: "${GDB_OAUTH_CLIENT_SECRET}"
      - name: "AUTH_SERVICE_CLIENT_SCOPE_1"
        value: "openid email profile"
      - name: "TRANSLATION_SERVICE_URL"
        value: "${TRANSLATION_SERVICE_URL}"
      - name: "AUTH_SERVICE_CLIENT_CALLBACK"
        value: "login/callback"
      - name: "LANGUAGES"
        value: "${DEFAULT_LANGUAGE}"
      - name: "DEMAND_AUTHORIZATION_HEADER"
        value: "true"
      - name: "UPLOAD_FILE_SIZE_LIMIT"
        value: "26214400"
      - name: "APP_TITLE"
        value: "${SYSTEM_CODE} gdb"
                                                                                                                 
