version: 2.1

parameters:
  namespace:
    type: string
    default: digital-registries-bb-emulator
  playground:
    type: boolean
    default: false
  image:
    type: string
    default: "bb/digital-registries/emulator"
  force_deploy:
    type: boolean
    default: false
  emulator-db-flush:
    type: boolean
    default: false

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  helm: circleci/helm@3.0

commands:
  build_and_deploy:
    parameters:
      deploy:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - helm/install_helm_client:
          version: v3.13.0
      - run:
          name: Setup env
          command: |
              echo "export IMAGE=${CONTAINER_REGISTRY}/<< pipeline.parameters.image >>" >> "$BASH_ENV"
      - run:
          name: Build docker image
          command: |
            cd emulator/implementation
            ./gradlew build bootBuildImage "--imageName=$IMAGE:latest"
      - run:
          name: Check Helm Chart
          command: |
            helm lint ./emulator/helm
      - when:
          condition: << parameters.deploy >>
          steps:
            - aws-cli/setup:
                role_arn: "${AWS_CIRCLECI_ROLE_ARN}"
                region: ${AWS_REGION}
                role_session_name: CircleCISession
                session_duration: '1800'
            - run:
                name: Push image
                command: |
                  aws ecr get-login-password | docker login --username AWS --password-stdin "${CONTAINER_REGISTRY}"
                  docker push "$IMAGE:latest"
            - run:
                name: Update kubeconfig
                command: |
                  aws eks update-kubeconfig --name ${EKS_CLUSTER}
            - run:
                name: Deploy project
                command: |
                  DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE:latest)
                  DIGEST="${DIGEST#*@}"
                  helm upgrade --wait --install --dependency-update --create-namespace \
                    --namespace << pipeline.parameters.namespace >> \
                    --set digital_registries_bb_emulator.dbPersist.flushStorageOnInit=<< pipeline.parameters.emulator-db-flush >> \
                    --set-string "digital_registries_bb_emulator.container.image=${IMAGE}@${DIGEST}" \
                    digital-registries-bb-emulator ./emulator/helm
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - build_and_deploy:
          deploy: false

  build-and-deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - build_and_deploy:
          deploy: true

workflows:
  "Just build":
    when:
      and:
        - equal: [ false, << pipeline.parameters.playground >> ]
        - equal: [ false, << pipeline.parameters.force_deploy >> ]
        - not:
            equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build:
          context: sandbox-dev

  # build and deploy to dev commits to main
  "Build and deploy to dev":
    when:
      and:
        - equal: [ false, << pipeline.parameters.playground >> ]
        - or:
          - equal: [ 'main', << pipeline.git.branch >> ]
          - equal: [ true, << pipeline.parameters.force_deploy >> ]
    jobs:
      - build-and-deploy:
          context: sandbox-dev

  # build and deploy to playground depending on parameter
  "Build and deploy to playground":
    when:
      and:
        - equal: [ true, << pipeline.parameters.playground >> ]
        - equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build-and-deploy:
          context: playground
