{{ if .Values.global.postgres }}
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  dbInstanceIdentifier: {{ .Values.postgres.name }}
  engine: {{ .Values.postgres.engine }}
  masterUsername: {{ .Values.postgres.masterUsername }}
  masterUserPassword:
    namespace: {{ .Values.postgres.masterUserPassword.namespace }}
    name: {{ .Values.postgres.masterUserPassword.name }}
    key: {{ .Values.postgres.masterUserPassword.key }}
  dbSubnetGroupName: {{ .Values.postgres.dbSubnetGroupName }}
  dbInstanceClass: {{ .Values.postgres.dbInstanceClass }}
  allocatedStorage: {{ .Values.postgres.allocatedStorage }}
  deletionProtection: {{ .Values.postgres.deletionProtection }}
{{ end }}  
