deployment:
  name: backend
  containers:
    name: open-imis-backend
    image: 161826879607.dkr.ecr.eu-central-1.amazonaws.com/open-imis/plg-backend:latest
    imagePullPolicy: "Always"
    port: 8000

service:
  name: backend
  port: 8000
  type: ClusterIP
  targetPort: 8000
