deployment:
  name: backend
  containers:
    name: open-imis-backend
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/open-imis/dev-backend:0.0.9
    imagePullPolicy: "Always"
    port: 8000

service:
  name: backend
  port: 8000
  type: ClusterIP
  targetPort: 8000
